# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DocumentWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox, QFileDialog


class Ui_documet_window(object):
    def setupUi(self, documet_window):
        documet_window.setObjectName("documet_window")
        documet_window.resize(838, 642)
        documet_window.setStyleSheet("background-color:#FFFBF5")
        self.centralwidget = QtWidgets.QWidget(documet_window)
        self.centralwidget.setObjectName("centralwidget")
        self.screenshot_section = QtWidgets.QLabel(self.centralwidget)
        self.screenshot_section.setGeometry(QtCore.QRect(160, 20, 521, 291))
        self.screenshot_section.setText("")
        self.screenshot_section.setObjectName("screenshot_section")
        self.comment_section = QtWidgets.QLineEdit(self.centralwidget)
        self.comment_section.setGeometry(QtCore.QRect(160, 380, 521, 131))
        self.comment_section.setText("")
        self.comment_section.setObjectName("comment_section")
        self.save_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_file_button.setGeometry(QtCore.QRect(370, 550, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_file_button.setFont(font)
        self.save_file_button.setStyleSheet("background-color:gray;")
        self.save_file_button.setObjectName("save_file_button")
        documet_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(documet_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 838, 22))
        self.menubar.setObjectName("menubar")
        documet_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(documet_window)
        self.statusbar.setObjectName("statusbar")
        documet_window.setStatusBar(self.statusbar)

        self.retranslateUi(documet_window)
        QtCore.QMetaObject.connectSlotsByName(documet_window)




    def retranslateUi(self, documet_window):
        _translate = QtCore.QCoreApplication.translate
        documet_window.setWindowTitle(_translate("documet_window", "MainWindow"))
        self.save_file_button.setText(_translate("documet_window", "Save as PDF"))






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    documet_window = QtWidgets.QMainWindow()
    ui = Ui_documet_window()
    ui.setupUi(documet_window)
    documet_window.show()
    sys.exit(app.exec_())
