# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1906, 897)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("/*\n"
"ManjaroMix Style Sheet for QT Applications\n"
"Author: Jaime A. Quiroga P.\n"
"Company: GTRONICK\n"
"Last updated: 25/02/2020, 15:42.\n"
"Available at: https://github.com/GTRONICK/QSS/blob/master/ManjaroMix.qss\n"
"*/\n"
"QMainWindow {\n"
"    background-color:#151a1e;\n"
"}\n"
"QCalendar {\n"
"    background-color: #151a1e;\n"
"}\n"
"QTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"    background-color: #222b2e;\n"
"    color: #d3dae3;\n"
"}\n"
"QPlainTextEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"    background-color: #222b2e;\n"
"    color: #d3dae3;\n"
"}\n"
"QToolButton {\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:hover{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(197, 197, 197), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(197, 197, 197));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(195, 195, 195), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"QToolButton:pressed{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QPushButton{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QPushButton::default{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #FFFFFF;\n"
"    padding: 2px;\n"
"    background-color: #151a1e;;\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #1c1f1f;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: solid;\n"
"    border-color: #050a0e;\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"    background-color: #2c2f2f;\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(217, 217, 217), stop:1 rgb(227, 227, 227));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.5, stop:0 rgb(227, 227, 227), stop:1 rgb(217, 217, 217));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgb(215, 215, 215), stop:1 rgb(222, 222, 222));\n"
"    border-width: 1px;\n"
"    border-radius: 5px;\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"    background-color: rgb(142,142,142);\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"    background-color: #222b2e;\n"
"    color: #d3dae3;\n"
"}\n"
"QLabel {\n"
"    color: #d3dae3;\n"
"}\n"
"QLCDNumber {\n"
"    color: #4d9b87;\n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: #d3dae3;\n"
"    border-radius: 10px;\n"
"    border-color: transparent;\n"
"    border-style: solid;\n"
"    background-color: #52595d;\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: #214037    ;\n"
"    border-radius: 10px;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #151a1e;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #d3dae3;\n"
"      spacing: 3px;\n"
"      padding: 1px 4px;\n"
"    background-color: #151a1e;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"      background-color: #252a2e;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu {\n"
"    background-color: #151a1e;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #252a2e;\n"
"    color: #FFFFFF;\n"
"}\n"
"QMenu::item {\n"
"    color: #d3dae3;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: #050a0e;\n"
"        background-color: #1e282c;\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-style: solid;\n"
"    border-left-width:1px;\n"
"    border-right-width:0px;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    border-top-left-radius: 4px;\n"
"    color: #d3dae3;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-left-width:1px;\n"
"    border-right-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-color: #050a0e;\n"
"    border-top-right-radius: 4px;\n"
"    color: #d3dae3;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabBar::tab {\n"
"    border-style: solid;\n"
"    border-top-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-left-width:1px;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    color: #d3dae3;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #151a1e;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"    border-bottom-width:0px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #1e282c;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:first:selected, QTabBar::tab:hover {\n"
"      border-style: solid;\n"
"      border-left-width:1px;\n"
"      border-bottom-width:0px;\n"
"      border-top-width:1px;\n"
"    border-right-color: transparent;\n"
"    border-top-color: #050a0e;\n"
"    border-left-color: #050a0e;\n"
"    border-bottom-color: #050a0e;\n"
"    color: #FFFFFF;\n"
"    padding: 3px;\n"
"    margin-left:0px;\n"
"    background-color: #1e282c;\n"
"}\n"
"\n"
"QCheckBox {\n"
"    color: #d3dae3;\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #000000;\n"
"    background-color: qradialgradient(cx:0.4, cy:0.4, radius: 1.5,fx:0, fy:0, stop:0 #1e282c, stop:0.3 #1e282c, stop:0.4 #4fa08b, stop:0.5 #1e282c, stop:1 #1e282c);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #000000;\n"
"}\n"
"QRadioButton {\n"
"    color: #d3dae3;\n"
"    padding: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #a9b7c6;\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.4,fx:0.5, fy:0.5, stop:0 #4fa08b, stop:1 #1e282c);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    border-style:solid;\n"
"    border-radius:5px;\n"
"    border-width: 1px;\n"
"    border-color: #4fa08b;\n"
"    color: #a9b7c6;\n"
"    background-color: transparent;\n"
"}\n"
"QStatusBar {\n"
"    color:#027f7f;\n"
"}\n"
"QSpinBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QDoubleSpinBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QTimeEdit {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QDateTimeEdit {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QDateEdit {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QFontComboBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"QComboBox {\n"
"    color: #d3dae3;\n"
"    background-color: #222b2e;\n"
"    border-width: 1px;\n"
"    border-style: solid;\n"
"    border-color: #4fa08b;\n"
"}\n"
"\n"
"QDial {\n"
"    background: #16a085;\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #222b2e;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#222b2e;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 5px;\n"
"    background-color: #52595d;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 5px;\n"
"    background-color: #52595d;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #1a2224;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #1a2224;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: #52595d;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background: #52595d;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: #15433a;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background-color: #15433a;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    max-height: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #58a492;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-width: 25px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #58a492;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: #15433a;\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-right-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: right;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: #15433a;\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-bottom-left-radius: 4px;\n"
"   border-bottom-right-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: bottom;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-bottom-left-radius: 4px;\n"
"   background: #15433a;\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-bottom-left-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   width: 20px;\n"
"   subcontrol-position: left;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-top-right-radius: 4px;\n"
"   background: #15433a;\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed {\n"
"   border: 2px transparent grey;\n"
"   border-top-left-radius: 4px;\n"
"   border-top-right-radius: 4px;\n"
"   background: rgb(181,181,181);\n"
"   height: 20px;\n"
"   subcontrol-position: top;\n"
"   subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"   background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"   background: none;\n"
"}\n"
"QTableWidget\n"
"{\n"
"font-color : white;\n"
"color : white;\n"
"background-color: black;\n"
"gridline-color: white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signals_name = QtWidgets.QComboBox(self.centralwidget)
        self.signals_name.setGeometry(QtCore.QRect(570, 35, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.signals_name.setFont(font)
        self.signals_name.setStyleSheet("")
        self.signals_name.setCurrentText("")
        self.signals_name.setObjectName("signals_name")
        self.pushButton_plot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot.setGeometry(QtCore.QRect(1090, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_plot.setFont(font)
        self.pushButton_plot.setStyleSheet("background-color: #4fa08b;")
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(820, 30, 91, 50))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkBox_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.color_picker_button = QtWidgets.QPushButton(self.centralwidget)
        self.color_picker_button.setGeometry(QtCore.QRect(760, 30, 31, 31))
        self.color_picker_button.setStyleSheet("background-color:red;")
        self.color_picker_button.setText("")
        self.color_picker_button.setIconSize(QtCore.QSize(10, 10))
        self.color_picker_button.setObjectName("color_picker_button")
        self.minus_button = QtWidgets.QPushButton(self.centralwidget)
        self.minus_button.setGeometry(QtCore.QRect(970, 40, 29, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.minus_button.setFont(font)
        self.minus_button.setStyleSheet("background-color: #4fa08b;")
        self.minus_button.setObjectName("minus_button")
        self.plus_button = QtWidgets.QPushButton(self.centralwidget)
        self.plus_button.setGeometry(QtCore.QRect(930, 40, 29, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.plus_button.setFont(font)
        self.plus_button.setStyleSheet("background-color: #4fa08b;")
        self.plus_button.setIconSize(QtCore.QSize(16, 16))
        self.plus_button.setObjectName("plus_button")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 110, 901, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_channel1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_channel1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_channel1.setObjectName("verticalLayout_channel1")
        self.graphicsView_channel1 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_2)
        self.graphicsView_channel1.setStyleSheet("background-color: #222b2e")
        self.graphicsView_channel1.setObjectName("graphicsView_channel1")
        self.verticalLayout_channel1.addWidget(self.graphicsView_channel1)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(940, 110, 941, 431))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_channel2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_channel2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_channel2.setObjectName("verticalLayout_channel2")
        self.graphicsView_channel2 = QtWidgets.QGraphicsView(self.verticalLayoutWidget_3)
        self.graphicsView_channel2.setStyleSheet("background-color: #222b2e")
        self.graphicsView_channel2.setObjectName("graphicsView_channel2")
        self.verticalLayout_channel2.addWidget(self.graphicsView_channel2)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(30, 550, 381, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_toolbar1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_toolbar1.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_toolbar1.setObjectName("verticalLayout_toolbar1")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(950, 550, 381, 41))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_toolbar2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_toolbar2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_toolbar2.setObjectName("verticalLayout_toolbar2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 660, 1861, 271))
        self.tableWidget.setStyleSheet("background-color: #222b2e;\n"
"QHeaderView {\n"
"                background-color: #4fa08b; /* Change this to your desired color */\n"
"                color: white; /* Text color */\n"
"}\n"
"\n"
"                     \n"
"QTableWidget\n"
"{\n"
"font-color : white;\n"
"color : white;\n"
"background-color: black;\n"
"gridline-color: white;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.pause_button = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button.setGeometry(QtCore.QRect(470, 550, 41, 41))
        self.pause_button.setObjectName("pause_button")
        self.pause_button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pause_button_2.setGeometry(QtCore.QRect(1390, 550, 41, 41))
        self.pause_button_2.setObjectName("pause_button_2")
        self.rewind_button1 = QtWidgets.QPushButton(self.centralwidget)
        self.rewind_button1.setGeometry(QtCore.QRect(420, 550, 41, 41))
        self.rewind_button1.setText("")
        self.rewind_button1.setObjectName("rewind_button1")
        self.rewind_button2 = QtWidgets.QPushButton(self.centralwidget)
        self.rewind_button2.setGeometry(QtCore.QRect(1340, 550, 41, 41))
        self.rewind_button2.setText("")
        self.rewind_button2.setObjectName("rewind_button2")
        self.link_button = QtWidgets.QRadioButton(self.centralwidget)
        self.link_button.setGeometry(QtCore.QRect(1020, 40, 51, 20))
        self.link_button.setObjectName("link_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1906, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_file = QtWidgets.QAction(MainWindow)
        self.open_file.setObjectName("open_file")
        self.make_pdf = QtWidgets.QAction(MainWindow)
        self.make_pdf.setObjectName("make_pdf")
        self.menuFile.addAction(self.open_file)
        self.menuFile.addAction(self.make_pdf)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_plot.setText(_translate("MainWindow", "Apply"))
        self.checkBox_2.setText(_translate("MainWindow", "Channel 1"))
        self.checkBox_3.setText(_translate("MainWindow", "Channel 2"))
        self.minus_button.setText(_translate("MainWindow", "➖"))
        self.plus_button.setText(_translate("MainWindow", "➕"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Signal "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mean"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Std"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Duration"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Min. Value"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Max. Value"))
        self.pause_button.setText(_translate("MainWindow", "❚❚"))
        self.pause_button_2.setText(_translate("MainWindow", "❚❚"))
        self.link_button.setText(_translate("MainWindow", "Link"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.open_file.setText(_translate("MainWindow", "Open file"))
        self.make_pdf.setText(_translate("MainWindow", "Make a PDF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
